name: Flutter CI/CD # saoud test app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.x  # Set to the Flutter version you need

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Linter
        run: flutter analyze

      - name: Run Tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact  # ✅ This step is MISSING in your workflow
        uses: actions/upload-artifact@v4
        with:
          name: release-apk  # Use a simple name
          path: build/app/outputs/flutter-apk/app-release.apk

  download:
    runs-on: ubuntu-latest
    needs: build  # Ensure this job runs after 'build'
    steps:
      - name: Download APK Artifact
        uses: actions/download-artifact@v4
        with:
          name: release-apk  # Must match the upload name
          path: extracted_apk  # Path where the APK will be downloaded

      - name: List Extracted Files
        run: ls -lh extracted_apk
